pipeline {
    agent any
    triggers {
        branch('main')
        branch('feature/*')
    }

    environment {
        NODE_VERSION = '14'
    }

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/bangarrc/CICD-Pipeline.git'
                sh 'npm install'
                sh 'npm run build'
                sh 'npm run test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'rsync -avz build/ user@server:/path/to/deployment/'
            }
        }
    }

    post {
        success {
            build job: 'Deploy-Production-Nextjs', parameters: []
        }
        failure {
            echo 'Deployment to staging failed!'
        }
    }
}
